## 列表

使用列表去汇总数据

In [2]:
a = [1, 2, 3, 4, 4] # 生成列表
print(a)

[1, 2, 3, 4, 4]


In [3]:
len(a)  # 获取列表长度

5

In [5]:
a[0]  # 访问元素

1

In [6]:
a[4] = 99   # 赋值
print(a)

[1, 2, 3, 4, 99]


In [7]:
a[0:2]  # 切片——左闭右开  a[0:2] = a[0],a[1]

[1, 2]

In [8]:
a[1:]  # 从索引1的地方道最后一个元素

[2, 3, 4, 99]

In [9]:
a[:3]  # 从第一个元素到索引为3的元素（不包括索引3的元素

[1, 2, 3]

In [11]:
a[:-1]  # 获取第一个元素到最后一个元素之间的元素

[1, 2, 3, 4]

## 字典

字典以键值对的形式存储数据

In [12]:
me = {'height': 180}  # 生成字典
me["height"]  #访问元素

180

In [13]:
me["weight"] = 70  # 添加新元素
print(me)

{'height': 180, 'weight': 70}


## if语句

if/else分支语句

In [14]:
hungry = True
if hungry:
    print("I'm hungry")

I'm hungry


In [15]:
hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm not hungry
I'm sleepy


## for语句
循环处理

In [16]:
for i in [1, 2, 3]:
    print(i)

1
2
3


## 函数
将一连串的处理定义成函数，需要使用时调用即可

In [17]:
def hello():
    print("Hello World")

hello()

Hello World


In [19]:
def hello(object):  # 传入参数
    print("Hello " + object + "!")

hello("cat")

Hello cat!


## 类

使用关键字`class`来定义类，遵循如下格式：
```python
class 类名:
    def __init__(self, 参数, ...):  # 构造函数
        ...
    def 方法名1(self, 参数, ...):  # 方法1
        ...
    def 方法名2(self, 参数, ...):  # 方法2
        ...
```

In [20]:
class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")
    def hello(self):
        print("hello, my name is " + self.name + "!")
    def good_bye(self):
        print("good-bye " + self.name + "!")

m = Man("David")
m.hello()
m.good_bye()

Initialized!
hello, my name is David!
good-bye David!


## `Numpy`

提供一些数组和矩阵的计算的方法

### 导入`numpy`

In [21]:
import numpy as np

### 生成`numpy`数组

In [22]:
x = np.array([1.0, 2.0, 3.0])
print(x)

[1. 2. 3.]


In [23]:
type(x)

numpy.ndarray

### `numpy`的算数运算

In [24]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y  # 对应元素相加

array([3., 6., 9.])

In [25]:
x - y  # 对应元素相减

array([-1., -2., -3.])

In [ ]:
x * y  # 对应元素相乘

array([ 2.,  8., 18.])

In [27]:
x / y

array([0.5, 0.5, 0.5])